<?
$InputElement = $Control->CreateElement(
	'input',
	[
		'type' => 'button',
	],
	[
		'Id' => 'id',
		'Form' => 'form',
		'Name' => 'name',
		'CssClass' => 'class',
		'Text' => 'value',
		'Disabled' => 'disabled',
	],
	$Parameters,
	null
);

if(isset($Parameters['Attributes'])) {
	foreach($Parameters['Attributes'] as $Attribute) {
		if(isset($Attribute['Value'])) {
			$InputElement->CreateAttribute(
				$Attribute['Name'],
				$Attribute['Value']
			);
		}
		else {
			$InputElement->CreateAttribute(
				$Attribute['Name'],
				null
			);
		}
	}
}

echo $InputElement;
?>