<?
if(isset($Parameters['Label'])) {
	$LabelElement = $Control->CreateElement(
		'label',
		[],
		[
			'Id' => 'for',
			'LabelCssClass' => 'class',
		],
		$Parameters,
		$Parameters['Label']
	);

	echo $LabelElement;
}

$SelectElement = $Control->CreateElement(
	'select',
	[
		'type' => 'text',
	],
	[
		'Id' => 'id',
		'Form' => 'form',
		'Name' => 'name',
		'CssClass' => 'class',
		'Disabled' => 'disabled',
	],
	$Parameters,
	null
);

if(isset($Parameters['Attributes'])) {
	foreach($Parameters['Attributes'] as $Attribute) {
		if(isset($Attribute['Value'])) {
			$SelectElement->CreateAttribute(
				$Attribute['Name'],
				$Attribute['Value']
			);
		}
		else {
			$SelectElement->CreateAttribute(
				$Attribute['Name'],
				null
			);
		}
	}
}

if(isset($Control->_Parameters['Options'])) {
	foreach($Control->_Parameters['Options'] as $Option) {
		if(isset($Parameters['Value'])) {
			if($Option['Value'] == $Parameters['Value']) {
				$Option['Selected'] = 'selected';
			}
		}

		$OptionElement = $Control->CreateElement(
			'option',
			[
				'Value' => $Option['Value'],
			],
			[
				'CssClass' => 'class',
				'Selected' => 'selected',
			],
			$Option,
			$Option['Text']
		);

		$SelectElement->AppendChild($OptionElement);
	}
}

echo $SelectElement;
?>