<?
if(isset($Parameters['IsChecked'])) {
	if(!$Parameters['IsChecked']) {
		unset($Parameters['IsChecked']);
	}
}

$InputElement = $Control->CreateElement(
	'input',
	[
		'type' => 'radio',
	],
	[
		'Id' => 'id',
		'Form' => 'form',
		'Name' => 'name',
		'CssClass' => 'class',
		'Value' => 'value',
		'IsChecked' => 'checked',
		'Disabled' => 'disabled',
	],
	$Parameters,
	null
);

if(isset($Parameters['Attributes'])) {
	foreach($Parameters['Attributes'] as $Attribute) {
		if(isset($Attribute['Value'])) {
			$InputElement->CreateAttribute(
				$Attribute['Name'],
				$Attribute['Value']
			);
		}
		else {
			$InputElement->CreateAttribute(
				$Attribute['Name'],
				null
			);
		}
	}
}

echo $InputElement;

if(isset($Parameters['Label'])) {
	$LabelElement = $Control->CreateElement(
		'label',
		[],
		[
			'Id' => 'for',
			'LabelCssClass' => 'class',
		],
		$Parameters,
		$Parameters['Label']
	);

	echo $LabelElement;
}
?>