<?
if(isset($Parameters['Label'])) {
	$LabelElement = $Control->CreateElement(
		'label',
		[],
		[
			'Id' => 'for',
			'LabelCssClass' => 'class',
		],
		$Parameters,
		$Parameters['Label']
	);

	echo $LabelElement;
}

$TextAreaElement = $Control->CreateElement(
	'textarea',
	[],
	[
		'Id' => 'id',
		'Form' => 'form',
		'Name' => 'name',
		'CssClass' => 'class',
		'Rows' => 'rows',
		'Disabled' => 'disabled',
		'Readonly' => 'readonly',
	],
	$Parameters,
	isset($Parameters['Value']) ? htmlspecialchars($Parameters['Value']) : null
);

if(isset($Parameters['Attributes'])) {
	foreach($Parameters['Attributes'] as $Attribute) {
		if(isset($Attribute['Value'])) {
			$TextAreaElement->CreateAttribute(
				$Attribute['Name'],
				$Attribute['Value']
			);
		}
		else {
			$TextAreaElement->CreateAttribute(
				$Attribute['Name'],
				null
			);
		}
	}
}

echo $TextAreaElement;
?>