<div class="<?=$Control->ClassName?>">
	<?
	if(isset($Control->Label[0])) {
		?><label for="<?=$Control->Id?>"><?=$Control->Label?></label><?
	}
	?>
	<div class="Input-TextBox"><input id="<?=$Control->Id?>" name="<?=$Control->Name?>" type="text" value="<?=$Control->Value?>" placeholder="<?=$Control->Placeholder?>"<?=0 < $Control->MaxLength ? ' maxlength="'.$Control->MaxLength.'"' : ''?> /></div>
	<?
	if(0 < count($Control->ErrorMessages)) {
		?><div class="Input-ErrorMessages"><?
			foreach($Control->ErrorMessages as $ErrorMessage) {
				?><p><?=$ErrorMessage?></p><?
			}
		?></div><?
	}
	?>
</div>