<?
$Attributes = '';

if(isset($Parameters['Id'])) {
	$Attributes .= ' id="'.$Parameters['Id'].'"';
}
else if(isset($Control->_Parameters['Id'])) {
	$Attributes .= ' id="'.$Control->_Parameters['Id'].'"';
}

if(isset($Control->_Parameters['Name'])) {
	$Attributes .= ' name="'.$Control->_Parameters['Name'].'"';
}

if(isset($Control->_Parameters['Form'])) {
	$Attributes .= ' form="'.$Control->_Parameters['Form'].'"';
}

$Attributes .= ' class="Button"';

$Attributes .= ' type="button"';

if(isset($Control->_Parameters['Text'])) {
	$Attributes .= ' value="'.$Control->_Parameters['Text'].'"';
}

?><input<?=$Attributes?> />