<?
$Attributes = '';

if(isset($Parameters['Id'])) {
	$Attributes .= ' id="'.$Parameters['Id'].'"';
}
else if(isset($Control->_Parameters['Id'])) {
	$Attributes .= ' id="'.$Control->_Parameters['Id'].'"';
}

if(isset($Control->_Parameters['Name'])) {
	$Attributes .= ' name="'.$Control->_Parameters['Name'].'"';
}

if(isset($Control->_Parameters['Form'])) {
	$Attributes .= ' form="'.$Control->_Parameters['Form'].'"';
}

$Attributes .= ' class="CheckBox"';

$Attributes .= ' type="checkbox"';

if(isset($Parameters['Value'])) {
	$Attributes .= ' value="'.$Parameters['Value'].'"';
}
else if(isset($Control->_Parameters['Value'])) {
	$Attributes .= ' value="'.$Control->_Parameters['Value'].'"';
}

if(isset($Parameters['IsChecked']) && $Parameters['IsChecked']) {
	$Attributes .= ' checked="checked"';
}
else if(isset($Control->_Parameters['IsChecked']) && $Control->_Parameters['IsChecked']) {
	$Attributes .= ' checked="checked"';
}

if(isset($Parameters['IsDisabled']) && $Parameters['IsDisabled']) {
	$Attributes .= ' disabled="disabled"';
}
else if(isset($Control->_Parameters['IsDisabled']) && $Control->_Parameters['IsDisabled']) {
	$Attributes .= ' disabled="disabled"';
}

?><input<?=$Attributes?> /><?

if(isset($Control->_Parameters['Label'])) {
	$Attributes = '';

	if(isset($Parameters['Id'])) {
		$Attributes .= ' for="'.$Parameters['Id'].'"';
	}
	else if(isset($Control->_Parameters['Id'])) {
		$Attributes .= ' for="'.$Control->_Parameters['Id'].'"';
	}

	$Attributes .= ' class="CheckBoxLabel"';

	?><label<?=$Attributes?>><?=$Control->_Parameters['Label']?></label><?
}

if(isset($Control->_Parameters['ShowErrorMessages']) && $Control->_Parameters['ShowErrorMessages'] && 0 < count($Control->_ErrorMessages)) {
	?><div class="ErrorMessages"><?
		foreach($Control->_ErrorMessages as $ErrorMessage) {
			?><p><?=$ErrorMessage?></p><?
		}
	?></div><?
}
?>