<?
if(isset($Control->_Parameters['Label'])) {
	$Attributes = '';

	if(isset($Control->_Parameters['Id'])) {
		$Attributes .= ' for="'.$Control->_Parameters['Id'].'"';
	}

	$Attributes .= ' class="TextAreaBoxLabel"';

	?><label<?=$Attributes?>><?=$Control->_Parameters['Label']?></label><?
}

$Attributes = '';

if(isset($Control->_Parameters['Id'])) {
	$Attributes .= ' id="'.$Control->_Parameters['Id'].'"';
}

if(isset($Control->_Parameters['Name'])) {
	$Attributes .= ' name="'.$Control->_Parameters['Name'].'"';
}

if(isset($Control->_Parameters['Form'])) {
	$Attributes .= ' form="'.$Control->_Parameters['Form'].'"';
}

$Attributes .= ' class="TextAreaBox"';

if(isset($Control->_Parameters['IsDisabled']) && $Control->_Parameters['IsDisabled']) {
	$Attributes .= ' disabled="disabled"';
}

if(isset($Control->_Parameters['IsReadOnly']) && $Control->_Parameters['IsReadOnly']) {
	$Attributes .= ' readonly="readonly"';
}

?><textarea<?=$Attributes?> /><?
	if(isset($Control->_Parameters['Value'])) {
		?><?=$Control->_Parameters['Value']?><?
	}
?></textarea><?

if(isset($Control->_Parameters['ShowErrorMessages']) && $Control->_Parameters['ShowErrorMessages'] && 0 < count($Control->_ErrorMessages)) {
	?><div class="ErrorMessages"><?
		foreach($Control->_ErrorMessages as $ErrorMessage) {
			?><p><?=$ErrorMessage?></p><?
		}
	?></div><?
}
?>