<?
if(isset($Control->_Parameters['Label'])) {
	$Attributes = '';

	if(isset($Parameters['Id'])) {
		$Attributes .= ' for="'.$Parameters['Id'].'"';
	}
	else if(isset($Control->_Parameters['Id'])) {
		$Attributes .= ' for="'.$Control->_Parameters['Id'].'"';
	}

	$Attributes .= ' class="TextBoxLabel"';

	?><label<?=$Attributes?>><?=$Control->_Parameters['Label']?></label><?
}

$Attributes = '';

if(isset($Parameters['Id'])) {
	$Attributes .= ' id="'.$Parameters['Id'].'"';
}
else if(isset($Control->_Parameters['Id'])) {
	$Attributes .= ' id="'.$Control->_Parameters['Id'].'"';
}

if(isset($Control->_Parameters['Name'])) {
	$Attributes .= ' name="'.$Control->_Parameters['Name'].'"';
}

if(isset($Control->_Parameters['Form'])) {
	$Attributes .= ' form="'.$Control->_Parameters['Form'].'"';
}

$Attributes .= ' class="TextBox"';

$Attributes .= ' type="text"';

if(isset($Parameters['Value'])) {
	$Attributes .= ' value="'.$Parameters['Value'].'"';
}
else if(isset($Control->_Parameters['Value'])) {
	$Attributes .= ' value="'.$Control->_Parameters['Value'].'"';
}

if(isset($Control->_Parameters['Placeholder'])) {
	$Attributes .= ' placeholder="'.$Control->_Parameters['Placeholder'].'"';
}

if(isset($Control->_Parameters['MaxLength'])) {
	$Attributes .= ' maxlength="'.$Control->_Parameters['MaxLength'].'"';
}

if(isset($Control->_Parameters['AutoComplete'])) {
	$Attributes .= ' autocomplete="'.$Control->_Parameters['AutoComplete'].'"';
}

if(isset($Control->_Parameters['IsDisabled']) && $Control->_Parameters['IsDisabled']) {
	$Attributes .= ' disabled="disabled"';
}

if(isset($Control->_Parameters['IsReadOnly']) && $Control->_Parameters['IsReadOnly']) {
	$Attributes .= ' readonly="readonly"';
}

?><input<?=$Attributes?> /><?

if(isset($Control->_Parameters['ShowErrorMessages']) && $Control->_Parameters['ShowErrorMessages'] && 0 < count($Control->_ErrorMessages)) {
	?><div class="ErrorMessages"><?
		foreach($Control->_ErrorMessages as $ErrorMessage) {
			?><p><?=$ErrorMessage?></p><?
		}
	?></div><?
}
?>