<div class="<?php  echo $this->ClassName; ?>">
	<div class="Input-CheckBox"><input id="<?=$this->Id?>" name="<?=$this->Name?>" type="checkbox" value="<?=$this->Value?>"<?=($this->IsChecked ? ' checked="checked"' : '')?> /></div>
	<label class="Input-CheckBoxLabel" for="<?php echo $this->Id; ?>"><?php echo $this->Label; ?></label>
	<div style="clear: left;"></div>
	<?php
	if(0 < count($this->ErrorMessages)) {
	?>
	<div class="Input-ErrorMessages">
		<?php
		foreach($this->ErrorMessages as $ErrorMessage) {
			echo '<p>', $ErrorMessage, '</p>';
		}
		?>
	</div>
	<?php
	}
	?>
</div>