<div class="<?php  echo $this->ClassName; ?>">
	<label for="<?php echo $this->Id; ?>"><?php echo $this->Label; ?></label>
	<div class="Input-TextBox"><input id="<?php echo $this->Id; ?>" name="<?php echo $this->Name; ?>" type="password" value="<?php echo $this->Value; ?>" placeholder="<?php echo $this->Placeholder; ?>" /></div>
	<?php
	if(0 < count($this->ErrorMessages)) {
	?>
	<div class="Input-ErrorMessages">
		<?php
		foreach($this->ErrorMessages as $ErrorMessage) {
			echo '<p>', $ErrorMessage, '</p>';
		}
		?>
	</div>
	<?php
	}
	?>
</div>