<input<?
	if(isset($Control->_Parameters['Id'])) {
		?> id="<?=$Control->_Parameters['Id']?>"<?
	}
	if(isset($Control->_Parameters['Name'])) {
		?> name="<?=$Control->_Parameters['Name']?>"<?
	}
	if(isset($Control->_Parameters['Form'])) {
		?> form="<?=$Control->_Parameters['Form']?>"<?
	}
	?> type="hidden"<?
	if(isset($Control->_Parameters['Value'])) {
		?> value="<?=$Control->_Parameters['Value']?>"<?
	}
	?> Newnorth:Control="HiddenControl"<?
?>/>