<div<?
if(isset($Control->_Parameters['CSS'])) {
	?> class="Input SubmitInput <?=$Control->_Parameters['CSS']?>"<?
}
else {
	?> class="Input SubmitInput"<?
}
?>><input<?
if(isset($Control->_Parameters['Id'])) {
	?> id="<?=$Control->_Parameters['Id']?>"<?
}
if(isset($Control->_Parameters['Name'])) {
	?> name="<?=$Control->_Parameters['Name']?>"<?
}
?> type="submit"<?
if(isset($Control->_Parameters['Text'])) {
	?> value="<?=$Control->_Parameters['Text']?>"<?
}
?> /></div>