<div<?
if(isset($Control->_Parameters['CSS'])) {
	?> class="Input TextAreaBoxInput <?=$Control->_Parameters['CSS']?>"<?
}
else {
	?> class="Input TextAreaBoxInput"<?
}
?>><?
	if(isset($Control->_Parameters['Label'])) {
		?><label<?
		if(isset($Control->_Parameters['Id'])) {
			?> for="<?=$Control->_Parameters['Id']?>"<?
		}
		?>><?=$Control->_Parameters['Label']?></label><?
	}
	?><textarea<?
	if(isset($Control->_Parameters['Id'])) {
		?> id="<?=$Control->_Parameters['Id']?>"<?
	}
	if(isset($Control->_Parameters['Name'])) {
		?> name="<?=$Control->_Parameters['Name']?>"<?
	}
	if(isset($Control->_Parameters['Form'])) {
		?> form="<?=$Control->_Parameters['Form']?>"<?
	}
	if($Control->_Parameters['IsDisabled']) {
		?> disabled="disabled"<?
	}
	if($Control->_Parameters['IsReadOnly']) {
		?> readonly="readonly"<?
	}
	?> Newnorth:Control="TextAreaBoxControl"><?
	if(isset($Control->_Parameters['Value'])) {
		?><?=$Control->_Parameters['Value']?><?
	}
	?></textarea><?
	?><div class="ErrorMessages" Newnorth:Control="ErrorMessagesControl"></div><?
	if(isset($Control->_Parameters['Id'])) {
		?><script language="javascript"><?
			?>window.addEventListener(<?
				?>"load",<?
				?>function(){<?
					?>element=document.getElementById("<?=$Control->_Parameters['Id']?>");<?
					if(isset($Control->_Parameters['Validators'])) {
						foreach($Control->_Parameters['Validators'] as $Validator) {
							?>element.AddValidator(function(){<?=$Validator['Owner']->$Validator['Method']($Control, $Validator['Parameters'])?>},"<?=$Validator['ErrorMessage']?>");<?
						}
					}
					if(isset($Control->_Parameters['ErrorMessages'])) {
						foreach($Control->_Parameters['ErrorMessages'] as $ErrorMessage) {
							?>element.ivErrorMessages.AddErrorMessage("<?=$ErrorMessage?>");<?
						}
					}
				?>}<?
			?>);<?
		?></script><?
	}
?></div>