<div class="Input <?=$Control->ClassName?>" Newnorth:Control="TextAreaBoxControl"><?
	if(isset($Control->Label[0])) {
		?><label for="<?=$Control->Id?>"><?=$Control->Label?></label><?
	}
	?><div class="TextAreaBox"><textarea id="<?=$Control->Id?>" name="<?=$Control->Name?>"><?=$Control->Value?></textarea></div><?
	?><div class="ErrorMessages"></div><?
	foreach($Control->ErrorMessages as $ErrorMessage) {
		?><p><?=$ErrorMessage?></p><?
	}
	?><script language="javascript"><?
		?>window.addEventListener(<?
			?>"load",<?
			?>function(){<?
				?>element=document.getElementById("<?=$Control->Id?>");<?
				foreach($Control->Validation as $Method => $Validation) {
					?>element.AddValidator(function(){<?=$Control->GetValidators()->{'Render'.$Method}($Control, $Validation)?>},"<?=$Validation['ErrorMessage']?>");<?
				}
				?>element.Validate();<?
			?>}<?
		?>);<?
	?></script><?
?></div>