<?
if(isset($Control->_Parameters['Label'])) {
	$Attributes = '';

	if(isset($Parameters['Id'])) {
		$Attributes .= ' for="'.$Parameters['Id'].'"';
	}
	else if(isset($Control->_Parameters['Id'])) {
		$Attributes .= ' for="'.$Control->_Parameters['Id'].'"';
	}

	if(isset($Control->_Parameters['LabelCssClass'])) {
		$Attributes .= ' class="'.$Control->_Parameters['LabelCssClass'].'"';
	}

	?><label<?=$Attributes?>><?=$Control->_Parameters['Label']?></label><?
}

$Attributes = '';

if(isset($Parameters['Id'])) {
	$Attributes .= ' id="'.$Parameters['Id'].'"';
}
else if(isset($Control->_Parameters['Id'])) {
	$Attributes .= ' id="'.$Control->_Parameters['Id'].'"';
}

if(isset($Control->_Parameters['Name'])) {
	$Attributes .= ' name="'.$Control->_Parameters['Name'].'"';
}

if(isset($Control->_Parameters['Form'])) {
	$Attributes .= ' form="'.$Control->_Parameters['Form'].'"';
}

if(isset($Control->_Parameters['CssClass'])) {
	$Attributes .= ' class="'.$Control->_Parameters['CssClass'].'"';
}

if(isset($Control->_Parameters['IsDisabled']) && $Control->_Parameters['IsDisabled']) {
	$Attributes .= ' disabled="disabled"';
}

?><select<?=$Attributes?>><?
	if(isset($Parameters['Value'])) {
		foreach($Control->_Parameters['Options'] as $Value => $Text) {
			$Value = (string)$Value;

			if((string)$Value === $Parameters['Value']) {
				?><option value="<?=$Value?>" selected="selected"><?=$Text?></option><?
			}
			else {
				?><option value="<?=$Value?>"><?=$Text?></option><?
			}
		}
	}
	else if(isset($Control->_Parameters['Value'])) {
		foreach($Control->_Parameters['Options'] as $Value => $Text) {
			$Value = (string)$Value;

			if($Value === $Control->_Parameters['Value']) {
				?><option value="<?=$Value?>" selected="selected"><?=$Text?></option><?
			}
			else {
				?><option value="<?=$Value?>"><?=$Text?></option><?
			}
		}
	}
	else {
		foreach($Control->_Parameters['Options'] as $Value => $Text) {
			$Value = (string)$Value;

			?><option value="<?=$Value?>"><?=$Text?></option><?
		}
	}
?></select><?

if(isset($Control->_Parameters['ShowErrorMessages']) && $Control->_Parameters['ShowErrorMessages'] && 0 < count($Control->_ErrorMessages)) {
	?><div class="ErrorMessages"><?
		foreach($Control->_ErrorMessages as $ErrorMessage) {
			?><p><?=$ErrorMessage?></p><?
		}
	?></div><?
}
?>