<?
$Attributes = '';

if(isset($Parameters['Id'])) {
	$Attributes .= ' id="'.$Parameters['Id'].'"';
}
else if(isset($Control->_Parameters['Id'])) {
	$Attributes .= ' id="'.$Control->_Parameters['Id'].'"';
}

if(isset($Control->_Parameters['Name'])) {
	$Attributes .= ' name="'.$Control->_Parameters['Name'].'"';
}

if(isset($Control->_Parameters['Form'])) {
	$Attributes .= ' form="'.$Control->_Parameters['Form'].'"';
}

if(isset($Control->_Parameters['CssClass'])) {
	$Attributes .= ' class="'.$Control->_Parameters['CssClass'].'"';
}

$Attributes .= ' type="submit"';

if(isset($Control->_Parameters['Text'])) {
	$Attributes .= ' value="'.$Control->_Parameters['Text'].'"';
}

if(isset($Control->_Parameters['Attributes'])) {
	foreach($Control->_Parameters['Attributes'] as $Name => $Value) {
		$Attributes .= ' '.$Name.'="'.$Value.'"';
	}
}

?><input<?=$Attributes?> />