<div<?
if(isset($Control->_Parameters['CSS'])) {
	?> class="Input ButtonInput <?=$Control->_Parameters['CSS']?>"<?
}
else {
	?> class="Input ButtonInput"<?
}
?>><input<?
if(isset($Control->_Parameters['Id'])) {
	?> id="<?=$Control->_Parameters['Id']?>"<?
}
if(isset($Control->_Parameters['Name'])) {
	?> name="<?=$Control->_Parameters['Name']?>"<?
}
if(isset($Control->_Parameters['Form'])) {
	?> form="<?=$Control->_Parameters['Form']?>"<?
}
?> type="button"<?
if(isset($Control->_Parameters['Text'])) {
	?> value="<?=$Control->_Parameters['Text']?>"<?
}
?> /></div>